<%@ Page Language="C#" MasterPageFile="~/admin/MasterPageAdmin.master" AutoEventWireup="true"
    CodeFile="vLookupEntry.aspx.cs" Inherits="admin_vLookupEntry" Title="World-Link System - Lookup Entry" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="at" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

    <style type="text/css">
        .select_box_pad
        {
            width: 325px;
            margin: 0px auto;
        }
        .employeeedit_text .input_label
        {
            width: 45%;
        }
        .CssTreeview
        {
            text-align: left;
            float: left;
            margin-left: 0px;
            padding-left: 0px;
            font-size: 14px;
            color: #72757c;
        }
        .CssTreeviewLeaf
        {
        	text-align: left !important;
            float: left;
            margin-left: 0px;
            padding-left: 0px;
            font-size: 12px;
            color:#ADADAD;
        }
    </style>
    <link media="screen" rel="stylesheet" href="../CSS/style.css" />
    <at:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server">
    </at:ToolkitScriptManager>
    <asp:UpdatePanel ID="upPanel" runat="server">
        <ContentTemplate>
            <div class="form_pad">
                <h4>
                    Manage Lookup Information</h4>
                <div>
                    <table width="100%">
                        <tr align="left">
                            <td height="80%" valign="top" align="left" width="20%">
                                <asp:Panel ID="pnTreeview" runat="server">
                                    <div>
                                            <asp:UpdatePanel ID="upPanelTreeview" runat="server">
                                                <ContentTemplate>
                                                    <asp:TreeView ID="TreeViewMain" runat="server" OnSelectedNodeChanged="TreeViewMain_SelectedNodeChanged"
                                                        OnTreeNodeCheckChanged="TreeViewMain_TreeNodeCheckChanged" ExpandDepth="2" 
                                                        NodeStyle-HorizontalPadding="0px" NodeStyle-VerticalPadding="0px" NodeIndent="0"
                                                        NodeWrap="True" ShowLines="True" NodeSpacing="0px" AutoGenerateDataBindings="False"
                                                        LineImagesFolder="~/Images/TreeLineImages">
                                                        <NodeStyle HorizontalPadding="0px" VerticalPadding="0px" CssClass="CssTreeview" />
                                                        <LeafNodeStyle CssClass="CssTreeviewLeaf" HorizontalPadding="0px" />
                                                    </asp:TreeView>
                                                </ContentTemplate>
                                            </asp:UpdatePanel>
                                </asp:Panel>
                            </td>
                            <td width="80%" valign="top">
                                <div id="dvErrorMsg" runat="server">
                                    <div class="form_top_co">
                                        <span>&nbsp;</span></div>
                                    <div class="form_box employeeedit_text clearfix">
                                        <span class="input_label">
                                            <asp:Label ID="lblErrorMsg" runat="server"></asp:Label>
                                        </span>
                                    </div>
                                    <div class="form_bot_co">
                                        <span>&nbsp;</span></div>
                                </div>
                                <table style="vertical-align: top" class="form_table">
                                    <tr>
                                        <td colspan="4">
                                            <div>
                                                <div class="form_top_co">
                                                    <span>&nbsp;</span></div>
                                                <div class="form_box employeeedit_text clearfix">
                                                    <span class="input_label">Lookup Category</span>
                                                    <asp:TextBox ID="txtLookupCat" runat="server" />
                                                    <asp:RequiredFieldValidator ID="rvtLookupCat" runat="server" ErrorMessage="Please enter Lookup Category" ControlToValidate="txtLookupCat"></asp:RequiredFieldValidator>
                                                </div>
                                                <div class="form_bot_co">
                                                    <span>&nbsp;</span></div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="4">
                                            <div>
                                                <div class="form_top_co">
                                                    <span>&nbsp;</span></div>
                                                <div class="form_box employeeedit_text clearfix">
                                                    <span class="input_label">Lookup SubCategory</span>
                                                    <asp:TextBox ID="txtLookupSubCat" runat="server" />
                                                    <asp:RequiredFieldValidator ID="rvLookupSubCat" runat="server" ErrorMessage="Please enter Lookup SubCategory" ControlToValidate="txtLookupSubCat"></asp:RequiredFieldValidator>
                                                </div>
                                                <div class="form_bot_co">
                                                    <span>&nbsp;</span></div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="4">
                                            <div>
                                                <div class="form_top_co">
                                                    <span>&nbsp;</span></div>
                                                <div class="form_box employeeedit_text clearfix">
                                                    <span class="input_label">Lookup icon</span>
                                                    <asp:FileUpload ID="FileUploadIcon" runat="server" />
                                                    &nbsp;&nbsp;&nbsp;<asp:Image ID="imgIcon" runat="server" Height="30px" Width="30px"
                                                        Visible="False" />
                                                </div>
                                                <div class="form_bot_co">
                                                    <span>&nbsp;</span></div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="4">
                                            <div>
                                                <div class="form_top_co">
                                                    <span>&nbsp;</span></div>
                                                <div class="form_box employeeedit_text clearfix">
                                                    <span class="input_label">Option Value</span>
                                                    <asp:TextBox ID="txtValue" runat="server" />
                                                </div>
                                                <div class="form_bot_co">
                                                    <span>&nbsp;</span></div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="1" align="center">
                                            <asp:LinkButton ID="btnSave" runat="server" class="grey2_btn aligncenter" OnClick="btnSave_Click"
                                                Visible="False">
                                                     <span>Submit</span></asp:LinkButton>
                                        </td>
                                        <td colspan="1" align="center">
                                            <asp:LinkButton ID="btnUpdate" runat="server" class="grey2_btn aligncenter" OnClick="btnUpdate_Click"
                                                Visible="False"> 
                                                    <span>Update</span></asp:LinkButton>
                                        </td>
                                        <td colspan="1" align="center">
                                            <asp:LinkButton ID="btnDelete" runat="server" class="grey2_btn aligncenter" OnClick="btnDelete_Click"
                                                Visible="False">
                                                     <span>Delete</span></asp:LinkButton>
                                        </td>
                                        <td colspan="1" align="left">
                                            <asp:LinkButton ID="btnCancel" runat="server" class="grey2_btn" 
                                                OnClick="btnCancel_Click" CausesValidation="False">
                                                 <span>Cancel</span></asp:LinkButton>
                                                  <div class="spacer25">
            </div>
             <asp:LinkButton ID="btnsendMail" runat="server" class="grey2_btn" 
                                                OnClick="btnsendMail_Click" CausesValidation="False">
                                                 <span>send Test</span></asp:LinkButton>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        
                    </table>
                </div>
            </div>
           
        </ContentTemplate>
        <Triggers> <asp:PostBackTrigger ControlID="btnSave" /> </Triggers>
    </asp:UpdatePanel>
    <script type="text/javascript">
        (function() {
            var mf = document.createElement("script"); mf.type = "text/javascript"; mf.async = true;
            mf.src = "//cdn.mouseflow.com/projects/6400d321-64cf-4fcb-a60d-a9e5ecdd0ee2.js";
            document.getElementsByTagName("head")[0].appendChild(mf);
        })();
</script>
 <script type="text/javascript">
     var title = document.getElementsByTagName("title")[0].innerHTML;
     var cid = "<%=Common.CompID %>";
     var uid = "<%= Common.UserID %>";
     var er = "<%= PageBase.IsError %>";
     var path = "/" + title + "/cid_" + cid + "&uid_" + uid + "&er_" + er + "";
     var mouseflowPath = path;
</script>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="Server">
</asp:Content>
